services:
  - type: web
    name: nutrisenegal
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONUNBUFFERED
        value: true
      - key: DATABASE_URL
        value: sqlite:///./nutrisenegal.db
